-- Generated by Oracle SQL Developer Data Modeler 3.1.0.687
--   at:        2014-12-27 10:08:24 IST
--   site:      Oracle Database 10g
--   type:      Oracle Database 10g



CREATE TABLE DSH_CAT 
    ( 
     Dsh_Cat_ID NUMBER (30)  NOT NULL , 
     Dsh_Cat_Nme VARCHAR2 (50 BYTE)  NOT NULL 
    ) 
;



ALTER TABLE DSH_CAT 
    ADD CONSTRAINT "Dish Category PK" PRIMARY KEY ( Dsh_Cat_ID ) ;


CREATE TABLE DSH_CAT_TYP 
    ( 
     Dish_Cat_Typ_ID NUMBER (30)  NOT NULL , 
     Dsh_Cat_ID NUMBER (30)  NOT NULL , 
     DSH_TYP_ID NUMBER (30)  NOT NULL 
    ) 
;



ALTER TABLE DSH_CAT_TYP 
    ADD CONSTRAINT "Dish Category Type PK" PRIMARY KEY ( Dish_Cat_Typ_ID ) ;


CREATE TABLE DSH_DTL 
    ( 
     Dsh_Dtl_ID NUMBER (30)  NOT NULL , 
     Dsh_PRc NUMBER (5,2)  NOT NULL , 
     DSH_AVL_STS_CDE VARCHAR2 (6 BYTE) , 
     Res_dtl_ID NUMBER (30)  NOT NULL , 
     DSH_MTDA_ID NUMBER  NOT NULL 
    ) 
;



ALTER TABLE DSH_DTL 
    ADD CONSTRAINT "Dish Details PK" PRIMARY KEY ( Dsh_Dtl_ID ) ;


CREATE TABLE DSH_MTDA 
    ( 
     DSH_MTDA_ID NUMBER  NOT NULL , 
     DSH_NME VARCHAR2 (500)  NOT NULL , 
     DFT_ING VARCHAR2 (500 BYTE) , 
     Dish_Cat_Typ_ID NUMBER (30)  NOT NULL , 
     DSH_CNT_CDE VARCHAR2 (6) , 
     Dsh_Cat_Typ_ID NUMBER (30)  NOT NULL 
    ) 
;



ALTER TABLE DSH_MTDA 
    ADD CONSTRAINT "Dish Metadata PK" PRIMARY KEY ( DSH_MTDA_ID ) ;


CREATE TABLE DSH_SYN 
    ( 
     DSH_SYN_ID NUMBER (30)  NOT NULL , 
     DSH_MTDA_ID NUMBER (30) , 
     DSH_SYN_MTDA_ID NUMBER (30) , 
     DSH_MTDA_ID1 NUMBER 
    ) 
;



ALTER TABLE DSH_SYN 
    ADD CONSTRAINT "Synonym Dish PK" PRIMARY KEY ( DSH_SYN_ID ) ;


CREATE TABLE DSH_TYP 
    ( 
     DSH_TYP_ID NUMBER (30)  NOT NULL , 
     Dsh_Typ_Nme VARCHAR2 (50 BYTE) 
    ) 
;



ALTER TABLE DSH_TYP 
    ADD CONSTRAINT "Dish Type PK" PRIMARY KEY ( DSH_TYP_ID ) ;


CREATE TABLE LGN_MTDA 
    ( 
     LGN_MTDA_DTL VARCHAR2 (20)  NOT NULL , 
     LGN_MTDA_ID NUMBER (10)  NOT NULL 
    ) 
;



ALTER TABLE LGN_MTDA 
    ADD CONSTRAINT LOGIN_METADATA_PK PRIMARY KEY ( LGN_MTDA_ID ) ;


CREATE TABLE REF_DTA 
    ( 
     REF_DTA_ID NUMBER (30)  NOT NULL , 
     REF_DTA_ITM VARCHAR2 (15 BYTE)  NOT NULL , 
     REF_DTA_ITM_CDE VARCHAR2 (6)  NOT NULL , 
     REF_DTA_ITM_VAL VARCHAR2 (100)  NOT NULL 
    ) 
;



ALTER TABLE REF_DTA 
    ADD CONSTRAINT REFERENCE_DATA_PK PRIMARY KEY ( REF_DTA_ID, REF_DTA_ITM ) ;


CREATE TABLE RES_CAT 
    ( 
     Res_Cat_ID NUMBER (10)  NOT NULL , 
     Res_Cat_Nme VARCHAR2 (20 BYTE)  NOT NULL 
    ) 
;



ALTER TABLE RES_CAT 
    ADD CONSTRAINT "PK_Restraunt Category" PRIMARY KEY ( Res_Cat_ID ) ;


CREATE TABLE RES_DTL 
    ( 
     Res_dtl_id NUMBER (30)  NOT NULL , 
     Res_nme VARCHAR2 (30 BYTE)  NOT NULL , 
     Lnd_lne_Nbr VARCHAR2 (100 BYTE) , 
     Mbl_Nbr VARCHAR2 (100 BYTE) , 
     Res_Cat_ID NUMBER (10)  NOT NULL 
    ) 
;



ALTER TABLE RES_DTL 
    ADD CONSTRAINT "Restraunt_Details PK" PRIMARY KEY ( Res_dtl_id ) ;


CREATE TABLE USR_DSH_LIK 
    ( 
     USR_DSH_DTL_ID NUMBER (30)  NOT NULL , 
     USR_DSH_LIK INTEGER , 
     USR_DSH_UNLIK INTEGER , 
     USR_ID NUMBER (30) , 
     Dsh_Dtl_ID NUMBER (30) 
    ) 
;



ALTER TABLE USR_DSH_LIK 
    ADD CONSTRAINT USER_DISH_DETAILS_PK PRIMARY KEY ( USR_DSH_DTL_ID ) ;


CREATE TABLE USR_DSH_RVW 
    ( 
     USR_DSH_RVW_ID NUMBER (30)  NOT NULL , 
     USR_DSH_CMT VARCHAR2 (4000 BYTE)  NOT NULL , 
     CRE_TMP TIMESTAMP  NOT NULL , 
     Dsh_Dtl_ID NUMBER (30) , 
     USR_ID NUMBER (30) 
    ) 
;



ALTER TABLE USR_DSH_RVW 
    ADD CONSTRAINT USER_DISH_REVIEW_PK PRIMARY KEY ( USR_DSH_RVW_ID ) ;


CREATE TABLE USR_MTDA 
    ( 
     USR_ID NUMBER (30)  NOT NULL , 
     USR_NME VARCHAR2 (50 BYTE)  NOT NULL , 
     USR_SUR_NME VARCHAR2 (50 BYTE)  NOT NULL , 
     USR_MBL_NBR VARCHAR2 (30 BYTE)  NOT NULL , 
     USR_STS_CDE VARCHAR2 (6)  NOT NULL , 
     CRE_TMP TIMESTAMP , 
     LST_UPD_TMP TIMESTAMP , 
     USR_LGN_ADDR VARCHAR2 (50 BYTE)  NOT NULL , 
     LGN_MTDA_ID NUMBER (10)  NOT NULL 
    ) 
;



ALTER TABLE USR_MTDA 
    ADD CONSTRAINT User_Metadata_PK PRIMARY KEY ( USR_ID ) ;



ALTER TABLE DSH_CAT_TYP 
    ADD CONSTRAINT Dsh_Cat_Typ_Fk1 FOREIGN KEY 
    ( 
     Dsh_Cat_ID
    ) 
    REFERENCES DSH_CAT 
    ( 
     Dsh_Cat_ID
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE DSH_CAT_TYP 
    ADD CONSTRAINT Dsh_Cat_Typ_Fk2 FOREIGN KEY 
    ( 
     DSH_TYP_ID
    ) 
    REFERENCES DSH_TYP 
    ( 
     DSH_TYP_ID
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE DSH_DTL 
    ADD CONSTRAINT Dsh_Dtl_Fk1 FOREIGN KEY 
    ( 
     Res_dtl_ID
    ) 
    REFERENCES RES_DTL 
    ( 
     Res_dtl_id
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE DSH_DTL 
    ADD CONSTRAINT Dsh_Dtl_Fk2 FOREIGN KEY 
    ( 
     DSH_MTDA_ID
    ) 
    REFERENCES DSH_MTDA 
    ( 
     DSH_MTDA_ID
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE DSH_MTDA 
    ADD CONSTRAINT Dsh_Mtda_Fk1 FOREIGN KEY 
    ( 
     Dish_Cat_Typ_ID
    ) 
    REFERENCES DSH_CAT_TYP 
    ( 
     Dish_Cat_Typ_ID
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE DSH_SYN 
    ADD CONSTRAINT Dsh_Syn_Fk1 FOREIGN KEY 
    ( 
     DSH_MTDA_ID1
    ) 
    REFERENCES DSH_MTDA 
    ( 
     DSH_MTDA_ID
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE RES_DTL 
    ADD CONSTRAINT Res_Dtl_Fk1 FOREIGN KEY 
    ( 
     Res_Cat_ID
    ) 
    REFERENCES RES_CAT 
    ( 
     Res_Cat_ID
    ) 
    ON DELETE CASCADE 
;


ALTER TABLE USR_DSH_LIK 
    ADD CONSTRAINT USR_DSH_LIK_FK1 FOREIGN KEY 
    ( 
     USR_ID
    ) 
    REFERENCES USR_MTDA 
    ( 
     USR_ID
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE USR_DSH_LIK 
    ADD CONSTRAINT USR_DSH_LIK_FK2 FOREIGN KEY 
    ( 
     Dsh_Dtl_ID
    ) 
    REFERENCES DSH_DTL 
    ( 
     Dsh_Dtl_ID
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE USR_DSH_RVW 
    ADD CONSTRAINT USR_DSH_RVW_FK1 FOREIGN KEY 
    ( 
     USR_ID
    ) 
    REFERENCES USR_MTDA 
    ( 
     USR_ID
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE USR_DSH_RVW 
    ADD CONSTRAINT USR_DSH__MTDA_FK2 FOREIGN KEY 
    ( 
     Dsh_Dtl_ID
    ) 
    REFERENCES DSH_DTL 
    ( 
     Dsh_Dtl_ID
    ) 
    ON DELETE SET NULL 
;


ALTER TABLE USR_MTDA 
    ADD CONSTRAINT USR_MTDA_FK FOREIGN KEY 
    ( 
     LGN_MTDA_ID
    ) 
    REFERENCES LGN_MTDA 
    ( 
     LGN_MTDA_ID
    ) 
    ON DELETE CASCADE 
;

--  ERROR: Invalid View VW_DSH_CNTNT 

















-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             25
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
